### ISSUE TITLE
Can I help?(Not an issue)

### ISSUE THREAD

**Issue by BK1603** [Nick-Winkler/client-side-todo-list#1]
Hey Nick (hope I can call you that), this is not really an issue and I apologize for posting this as an issue ':D, but I couldn't find any contact details of yours on your profile page, and I really want to contribute to some open source projects and I found this while searching for some, so can I contribute to this? I'd really like to help you make it better!

**Comment by BK1603** [comment]
Even I got late 😅
And I too am just a beginner 
I'd like to work on the features with you, just, umm name a few here which you'd like to see in the project and maybe I could help.

Looking forward to the suggestions man! Hope I can help 😀

**Comment by Nick-Winkler** [comment]
Sounds good! If I think of any additional features to add, I'll put them down as issues on the repository. That way there will be a working list of potential features. If there's one you want to take on, just comment on it (like you've already done), and say you're working on it. I'll do the same when I take on one of the tasks.
