### ISSUE TITLE
Add strikethrough css class to list items on click

### ISSUE THREAD

**Issue by Nick-Winkler** [Nick-Winkler/client-side-todo-list#2]
Putting this one out here in case anyone wants to give it a shot. This is a pretty basic feature that I was going to add, but I might as well give other people a chance to contribute if they want!

I'd like to add a feature to the todo list where when a user clicks on one of the list items, it would toggle a css class that gives it the strikethrough text decoration.

My thought is to add another function that toggles the class of the item, put it in an event listener, and add that to the addToList function. Very similar to the removeEl function was set up for the del Button. And naturally, the new class would need to be added to the css file too.

**Comment by BK1603** [comment]
I'd like to work on this one (and eventually on the next one too ya know 😁)

Starting today!

**Comment by BK1603** [comment]
The strike through function is ready, though, would you like to change the delete button to checkboxes?  Like the user ticks the checkbox and its struck through?
The PR is ready(without checkboxes), though let me know if you would like that feature, else I will commit it. 😄

**Comment by Nick-Winkler** [comment]
@BK1603 Hmm, I'm not seeing a pull request here. Could you check to make sure that it was created on this repo?

In regards to the checkbox method, I think that could be a great way to implement it, as it would make it easy to add additional styling options that way in the future. Great idea!

**Comment by BK1603** [comment]
@Nick-Winkler  Okay, I am working on the checkbox implementation, and will post the final pr, dunno what happened to the previous one, maybe its my network 😅 , but this shouldn't take long.

**Comment by BK1603** [comment]
@Nick-Winkler I have made the PR, hope you get it this time 😅

**Comment by Nick-Winkler** [comment]
@BK1603 I received the PR, checked the code, and merged it to the master branch. Great job! 👍

**Comment by BK1603** [comment]
@Nick-Winkler So finally I had my first PR accepted!!! 😋
THANKS A TON!
