### ISSUE TITLE
Add ability to change font-family for the app

### ISSUE THREAD

**Issue by Nick-Winkler** [Nick-Winkler/client-side-todo-list#4]
I think it could be fun to add a feature where the user could change the fonts on the app using a couple buttons or a dropdown menu at the top of the page. It could just be something as simple as one sans-serif font and on serif font available.

**Comment by BK1603** [comment]
I will be working on this one now, but before I do, please tell me that should the dropdown list be just there at the top, or behind some settings thing?

**Comment by Nick-Winkler** [comment]
@BK1603 I think it should be a the top for now. Once there's enough features (I think more than 5 is enough), then that's when it would be useful to add a settings menu. But for now, I think having it at the top would be the most effective placement.

Thanks for asking!

**Comment by BK1603** [comment]
@Nick-Winkler On it!

**Comment by BK1603** [comment]
Sorry I got late :sweat_smile: like weakends are over and so I got college, just to notify that the work is in progress, should send the PR soon :smile:

**Comment by BK1603** [comment]
@Nick-Winkler welcome :smile: and that's weekends :sweat_smile: also one last think since you are online here, like, are you on some other social media site where you don't mind me texting you :sweat_smile: cause like it often happens that I have something to ask or suggest but I can't really get to the laptop, and later on I totally forget :sweat_smile:

**Comment by Nick-Winkler** [comment]
@BK1603 I don't really do too much on other social media sites, but if you have email on your phone, you can email my dev email at nickwinklerdev@gmail.com. I'm usually pretty quick to respond on that. 

Would that be better?

**Comment by BK1603** [comment]
That would be amazing! And I will make sure I don't bombard you with a lot of emails :sweat_smile: Once again thanks a ton!

**Comment by Nick-Winkler** [comment]
@BK1603 I'm adding a private label to this, so that people know not to submit pull requests for this. I can't assign this to you, so using the private label seems to be the best workaround I have right now.

**Comment by BK1603** [comment]
Thanks a lot @Nick-Winkler
And I think this will work :)
Will be working on this today :)

**Comment by Nick-Winkler** [comment]
@BK1603 Since we now have this feature functional, I'm going to close this issue. But when we eventually tidy everything up and add styling and structure to the page, we will probably revisit this so that it fits nicely on the page (wherever we decide to put it).

**Comment by BK1603** [comment]
@Nick-Winkler
Roger that!
